image: python:2.7-alpine

before_script:
    - pip install --requirement test_requirements.txt

stages:
    - test
    - qa

test:2.7:
    stage: test
    script: py.test --cov

qa:
    stage: qa
    script: flake8 *.py resources/
