language: python
python:
  - "2.7"
sudo: false

install:
  - pip install --requirement test_requirements.txt
  - pip install codecov

script:
  - py.test --cov
  - flake8 *.py resources/

after_success:
  - codecov
